name: CMake

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-latest-vs-cmake
            os: windows-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: '-G "Visual Studio 17 2022" -DUHDR_BUILD_TESTS=1 -DUHDR_ENABLE_INSTALL=0 -DUHDR_BUILD_DEPS=1 -DUHDR_BUILD_FUZZERS=0'

          - name: windows-latest-vs-cmake-nogles
            os: windows-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: '-G "Visual Studio 17 2022" -DUHDR_BUILD_TESTS=1 -DUHDR_ENABLE_INSTALL=0 -DUHDR_BUILD_DEPS=1 -DUHDR_BUILD_FUZZERS=0 -DUHDR_ENABLE_GLES=0'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev

    - name: Configure CMake
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.cmake-opts }}

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_TYPE}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cmake-build-output
        path: ${{github.workspace}}/out/**/*